import * as fs from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";

// Fetch OpenAPI spec from backend
const BACKEND_URL = process.env.VITE_BACKEND_URL || "http://localhost:3000";
const OPENAPI_URL = `${BACKEND_URL}/documentation/json`;

console.log(`Fetching OpenAPI spec from: ${OPENAPI_URL}`);

const ast = await openapiTS(OPENAPI_URL);

const contents = astToString(ast);

fs.writeFileSync(
  new URL("../src/types/api.d.ts", import.meta.url),
  [
    '// This file is generated by running "npm run sync-schema". Do not modify it manually.',
    contents,
    "",
  ].join("\n"),
);

console.log("✓ API types generated successfully at src/types/api.d.ts");
