// This file is generated by running "npm run sync-schema". Do not modify it manually.
export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            timestamp?: string;
                            database?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/codebooks/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all codebook entries by type */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    type: "faculty" | "field_of_study" | "high_school_profession" | "city";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                id?: string;
                                /** @enum {string} */
                                type?: "faculty" | "field_of_study" | "high_school_profession" | "city";
                                name?: string;
                                createdAt?: string;
                                updatedAt?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/codebooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a codebook entry */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "faculty" | "field_of_study" | "high_school_profession" | "city";
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                id?: string;
                                /** @enum {string} */
                                type?: "faculty" | "field_of_study" | "high_school_profession" | "city";
                                name?: string;
                                createdAt?: string;
                                updatedAt?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/codebooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Update a codebook entry */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                id?: string;
                                /** @enum {string} */
                                type?: "faculty" | "field_of_study" | "high_school_profession" | "city";
                                name?: string;
                                createdAt?: string;
                                updatedAt?: string;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        /** @description Delete a codebook entry */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all students with filters */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    facultyId?: string;
                    fieldOfStudyId?: string;
                    isCurrentStudent?: "true" | "false";
                    isEmployed?: "true" | "false";
                    isWorkingInField?: "true" | "false";
                    page?: string;
                    limit?: string;
                    sort?: "lastName" | "firstName" | "facultyName" | "fieldOfStudyName" | "createdAt";
                    order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                id?: string;
                                firstName?: string;
                                lastName?: string;
                                fatherName?: string;
                                email?: string;
                                address?: string;
                                phone?: string;
                                isCurrentStudent?: boolean;
                                isEmployed?: boolean;
                                isWorkingInField?: boolean;
                                /** @enum {string} */
                                highSchoolType?: "gimnazija" | "strukovna";
                                /** @enum {string} */
                                highSchoolDuration?: "trogodisnja" | "cetverogodisnja" | "petogodisnja";
                                highSchoolProfessionId?: string | null;
                                highSchoolCityId?: string;
                                highSchoolProfessionName?: string | null;
                                highSchoolCityName?: string;
                                facultyId?: string;
                                fieldOfStudyId?: string;
                                facultyCityId?: string;
                                facultyName?: string;
                                fieldOfStudyName?: string;
                                facultyCityName?: string;
                                createdAt?: string;
                                updatedAt?: string;
                            }[];
                            meta?: {
                                page?: number;
                                limit?: number;
                                total?: number;
                                totalPages?: number;
                                hasNextPage?: boolean;
                                hasPreviousPage?: boolean;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** @description Register as a student (public form) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        firstName: string;
                        lastName: string;
                        fatherName: string;
                        /** Format: email */
                        email: string;
                        address: string;
                        phone: string;
                        isCurrentStudent: boolean;
                        isEmployed: boolean;
                        isWorkingInField?: boolean;
                        /** @enum {string} */
                        highSchoolType: "gimnazija" | "strukovna";
                        /** @enum {string} */
                        highSchoolDuration: "trogodisnja" | "cetverogodisnja" | "petogodisnja";
                        highSchoolProfessionId?: string;
                        highSchoolCityId: string;
                        customHighSchoolProfessionName?: string;
                        customCityName?: string;
                        facultyId: string;
                        fieldOfStudyId: string;
                        facultyCityId: string;
                        customFacultyName?: string;
                        customFieldOfStudyName?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                id?: string;
                                firstName?: string;
                                lastName?: string;
                                fatherName?: string;
                                email?: string;
                                address?: string;
                                phone?: string;
                                isCurrentStudent?: boolean;
                                isEmployed?: boolean;
                                isWorkingInField?: boolean;
                                /** @enum {string} */
                                highSchoolType?: "gimnazija" | "strukovna";
                                /** @enum {string} */
                                highSchoolDuration?: "trogodisnja" | "cetverogodisnja" | "petogodisnja";
                                highSchoolProfessionId?: string | null;
                                highSchoolCityId?: string;
                                highSchoolProfessionName?: string | null;
                                highSchoolCityName?: string;
                                facultyId?: string;
                                fieldOfStudyId?: string;
                                facultyCityId?: string;
                                facultyName?: string;
                                fieldOfStudyName?: string;
                                facultyCityName?: string;
                                createdAt?: string;
                                updatedAt?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get student by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                id?: string;
                                firstName?: string;
                                lastName?: string;
                                fatherName?: string;
                                email?: string;
                                address?: string;
                                phone?: string;
                                isCurrentStudent?: boolean;
                                isEmployed?: boolean;
                                isWorkingInField?: boolean;
                                /** @enum {string} */
                                highSchoolType?: "gimnazija" | "strukovna";
                                /** @enum {string} */
                                highSchoolDuration?: "trogodisnja" | "cetverogodisnja" | "petogodisnja";
                                highSchoolProfessionId?: string | null;
                                highSchoolCityId?: string;
                                highSchoolProfessionName?: string | null;
                                highSchoolCityName?: string;
                                facultyId?: string;
                                fieldOfStudyId?: string;
                                facultyCityId?: string;
                                facultyName?: string;
                                fieldOfStudyName?: string;
                                facultyCityName?: string;
                                createdAt?: string;
                                updatedAt?: string;
                            };
                        };
                    };
                };
            };
        };
        /** @description Update student */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        firstName?: string;
                        lastName?: string;
                        fatherName?: string;
                        /** Format: email */
                        email?: string;
                        address?: string;
                        phone?: string;
                        isCurrentStudent?: boolean;
                        isEmployed?: boolean;
                        isWorkingInField?: boolean;
                        /** @enum {string} */
                        highSchoolType?: "gimnazija" | "strukovna";
                        /** @enum {string} */
                        highSchoolDuration?: "trogodisnja" | "cetverogodisnja" | "petogodisnja";
                        highSchoolProfessionId?: string | null;
                        highSchoolCityId?: string;
                        customHighSchoolProfessionName?: string;
                        customCityName?: string;
                        facultyId?: string;
                        fieldOfStudyId?: string;
                        facultyCityId?: string;
                        customFacultyName?: string;
                        customFieldOfStudyName?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                id?: string;
                                firstName?: string;
                                lastName?: string;
                                fatherName?: string;
                                email?: string;
                                address?: string;
                                phone?: string;
                                isCurrentStudent?: boolean;
                                isEmployed?: boolean;
                                isWorkingInField?: boolean;
                                /** @enum {string} */
                                highSchoolType?: "gimnazija" | "strukovna";
                                /** @enum {string} */
                                highSchoolDuration?: "trogodisnja" | "cetverogodisnja" | "petogodisnja";
                                highSchoolProfessionId?: string | null;
                                highSchoolCityId?: string;
                                highSchoolProfessionName?: string | null;
                                highSchoolCityName?: string;
                                facultyId?: string;
                                fieldOfStudyId?: string;
                                facultyCityId?: string;
                                facultyName?: string;
                                fieldOfStudyName?: string;
                                facultyCityName?: string;
                                createdAt?: string;
                                updatedAt?: string;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        /** @description Delete student */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get student statistics for dashboard */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                total?: number;
                                currentStudents?: number;
                                formerStudents?: number;
                                employed?: number;
                                unemployed?: number;
                                workingInField?: number;
                                notWorkingInField?: number;
                                byFaculty?: {
                                    facultyId?: string;
                                    facultyName?: string;
                                    count?: number;
                                }[];
                                byFieldOfStudy?: {
                                    fieldOfStudyId?: string;
                                    fieldOfStudyName?: string;
                                    count?: number;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send bulk SMS to selected students (prints to console) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        studentIds: string[];
                        messageTemplate: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                sent?: number;
                                messages?: {
                                    phone?: string;
                                    studentName?: string;
                                    message?: string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send bulk email to selected students */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        studentIds: string[];
                        subject: string;
                        messageTemplate: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                sent?: number;
                                total?: number;
                                results?: {
                                    email?: string;
                                    studentName?: string;
                                    success?: boolean;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

